---------------------------------------------------------
-- Tablas de ejemplo
---------------------------------------------------------
CREATE TABLE clientes (
  id_cliente     VARCHAR2(20) PRIMARY KEY,
  nombre         VARCHAR2(100),
  documento      VARCHAR2(50),
  email          VARCHAR2(100),
  telefono       VARCHAR2(20)
);

CREATE TABLE vehiculos (
  vin            VARCHAR2(50) PRIMARY KEY,
  marca          VARCHAR2(50),
  modelo         VARCHAR2(50),
  ano            NUMBER(4),
  precio         NUMBER(12,2)
);

CREATE TABLE compras (
  id_compra      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente     VARCHAR2(20),
  vin            VARCHAR2(50),
  id_item        VARCHAR2(20),
  descripcion    VARCHAR2(200),
  cantidad       NUMBER,
  valor          NUMBER(12,2),
  FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente),
  FOREIGN KEY (vin) REFERENCES vehiculos(vin)
);

COMMIT;


